import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const POPULAR_STOCKS = [
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corporation' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'TSLA', name: 'Tesla, Inc.' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation' },
  { ticker: 'META', name: 'Meta Platforms Inc.' },
  { ticker: 'NFLX', name: 'Netflix, Inc.' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'COIN', name: 'Coinbase Global Inc.' },
  { ticker: 'PLTR', name: 'Palantir Technologies' },
  { ticker: 'SPY', name: 'S&P 500 ETF' },
];

export const SEARCHABLE_STOCKS = [
  ...POPULAR_STOCKS,
  { ticker: 'BABA', name: 'Alibaba Group' },
  { ticker: 'DIS', name: 'The Walt Disney Company' },
  { ticker: 'BA', name: 'Boeing Company' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'HD', name: 'The Home Depot' },
  { ticker: 'MA', name: 'Mastercard Inc.' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'CRM', name: 'Salesforce Inc.' },
  { ticker: 'INTC', name: 'Intel Corporation' },
  { ticker: 'CSCO', name: 'Cisco Systems' },
  { ticker: 'PEP', name: 'PepsiCo Inc.' },
  { ticker: 'KO', name: 'The Coca-Cola Company' },
  { ticker: 'NKE', name: 'Nike Inc.' },
  { ticker: 'MCD', name: 'McDonald\'s Corporation' },
  { ticker: 'ORCL', name: 'Oracle Corporation' },
  { ticker: 'IBM', name: 'IBM' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.' },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'SHOP', name: 'Shopify Inc.' },
  { ticker: 'SQ', name: 'Block Inc.' },
  { ticker: 'UBER', name: 'Uber Technologies' },
  { ticker: 'LYFT', name: 'Lyft Inc.' },
  { ticker: 'ABNB', name: 'Airbnb Inc.' },
  { ticker: 'SNAP', name: 'Snap Inc.' },
  { ticker: 'TWTR', name: 'Twitter Inc.' },
  { ticker: 'SPOT', name: 'Spotify Technology' },
  { ticker: 'ZM', name: 'Zoom Video Communications' },
  { ticker: 'DOCU', name: 'DocuSign Inc.' },
  { ticker: 'ROKU', name: 'Roku Inc.' },
  { ticker: 'DKNG', name: 'DraftKings Inc.' },
  { ticker: 'RBLX', name: 'Roblox Corporation' },
  { ticker: 'U', name: 'Unity Software Inc.' },
  { ticker: 'NET', name: 'Cloudflare Inc.' },
  { ticker: 'SNOW', name: 'Snowflake Inc.' },
  { ticker: 'DDOG', name: 'Datadog Inc.' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings' },
  { ticker: 'ZS', name: 'Zscaler Inc.' },
  { ticker: 'OKTA', name: 'Okta Inc.' },
  { ticker: 'PANW', name: 'Palo Alto Networks' },
  { ticker: 'FTNT', name: 'Fortinet Inc.' },
  { ticker: 'MDB', name: 'MongoDB Inc.' },
  { ticker: 'TEAM', name: 'Atlassian Corporation' },
  { ticker: 'WDAY', name: 'Workday Inc.' },
  { ticker: 'NOW', name: 'ServiceNow Inc.' },
  { ticker: 'VEEV', name: 'Veeva Systems' },
  { ticker: 'SPLK', name: 'Splunk Inc.' },
  { ticker: 'TTD', name: 'The Trade Desk' },
  { ticker: 'MELI', name: 'MercadoLibre Inc.' },
  { ticker: 'SE', name: 'Sea Limited' },
  { ticker: 'BKNG', name: 'Booking Holdings' },
  { ticker: 'EXPE', name: 'Expedia Group' },
];
